-file("/home/helder/.asdf/installs/erlang/28.0.1/lib/parsetools-2.7/include/leexinc.hrl", 0).
%%
%% %CopyrightBegin%
%%
%% SPDX-License-Identifier: BSD-2-Clause
%%
%% Copyright (c) 2008,2009 Robert Virding. All rights reserved.
%% Copyright Ericsson AB 2009-2025. All Rights Reserved.
%%
%% Redistribution and use in source and binary forms, with or without
%% modification, are permitted provided that the following conditions
%% are met:
%%
%% 1. Redistributions of source code must retain the above copyright
%% notice, this list of conditions and the following disclaimer.
%% 2. Redistributions in binary form must reproduce the above copyright
%% notice, this list of conditions and the following disclaimer in the
%% documentation and/or other materials provided with the distribution.
%%
%% THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
%% "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
%% LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
%% FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
%% COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
%% INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
%% BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
%% LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
%% CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
%% LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
%% ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
%% POSSIBILITY OF SUCH DAMAGE.
%%
%% %CopyrightEnd%
%% 

%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(lx_lexer).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([tokenize/1,tokenize/2]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("leex/lx_lexer.xrl", 94).

strip_quotes([$" | Rest]) ->
    case lists:reverse(Rest) of
        [$" | Content] -> lists:reverse(Content);
        _ -> Rest
    end.

strip_colon([$: | Rest]) ->
    list_to_atom(Rest).
-file("/home/helder/.asdf/installs/erlang/28.0.1/lib/parsetools-2.7/include/leexinc.hrl", 47).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

%% string(InChars) ->
%% string(InChars, Loc) ->
%% {ok,Tokens,EndLoc} | {error,ErrorInfo,EndLoc}.
%% Loc is the starting location of the token, while EndLoc is the first not scanned
%% location. Location is either Line or {Line,Column}, depending on the "error_location" option.

string(Ics) -> 
    string(Ics,1).
string(Ics,L0) -> 
    string(Ics, L0, 1, Ics, []).
string(Ics, L0, C0, Tcs, Ts) -> 
    case do_string(Ics, L0, C0, Tcs, Ts) of
        {ok, T, {L,_}} -> {ok, T, L};
        {error, {{EL,_},M,D}, {L,_}} ->
            EI = {EL,M,D},
            {error, EI, L}
    end.

do_string([], L, C, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),{L,C}};
do_string(Ics0, L0, C0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, C0, 0, reject, 0) of
        {A,Alen,Ics1,L1,_C1} ->                  % Accepting end state
            C2 = adjust_col(Tcs, Alen, C0),
            string_cont(Ics1, L1, C2, yyaction(A, Alen, Tcs, L0, C0), Ts);
        {A,Alen,Ics1,L1,_C1,_S1} ->              % Accepting transition state
            C2 = adjust_col(Tcs, Alen, C0),
            string_cont(Ics1, L1, C2, yyaction(A, Alen, Tcs, L0, C0), Ts);
        {reject,_Alen,Tlen,_Ics1,_L1,_C1,_S1} ->  % After a non-accepting state
            {error,{{L0, C0} ,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},{L0, C0}};
        {A,Alen,Tlen,_Ics1,L1, C1,_S1}->
            Tcs1 = yysuf(Tcs, Alen),
            L2 = adjust_line(Tlen, Alen, Tcs1, L1),
            C2 = adjust_col(Tcs, Alen, C1),
            string_cont(Tcs1, L2, C2, yyaction(A, Alen, Tcs, L0,C0), Ts)
    end.

%% string_cont(RestChars, Line, Col, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

-dialyzer({nowarn_function, string_cont/5}).

string_cont(Rest, Line, Col, {token,T}, Ts) ->
    do_string(Rest, Line, Col, Rest, [T|Ts]);
string_cont(Rest, Line, Col, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    do_string(NewRest, Line, Col, NewRest, [T|Ts]);
string_cont(Rest, Line, Col, {end_token,T}, Ts) ->
    do_string(Rest, Line, Col, Rest, [T|Ts]);
string_cont(Rest, Line, Col, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    do_string(NewRest, Line, Col, NewRest, [T|Ts]);
string_cont(Rest, Line, Col, skip_token, Ts) ->
    do_string(Rest, Line, Col, Rest, Ts);
string_cont(Rest, Line, Col, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    do_string(NewRest, Line, Col, NewRest, Ts);
string_cont(_Rest, Line, Col, {error,S}, _Ts) ->
    {error,{{Line, Col},?MODULE,{user,S}},{Line,Col}}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Loc) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,CurrCol,TokenChars,TokenLen,TokenLine,TokenCol,AccAction,AccLen}

token(Cont,Chars) -> 
    token(Cont,Chars,1).
token(Cont, Chars, Line) -> 
    case do_token(Cont,Chars,Line,1) of
        {more, _} = C -> C;
        {done, Ret0, R} ->
            Ret1 = case Ret0 of
                {ok, T, {L,_}} -> {ok, T, L};
                {eof, {L,_}} -> {eof, L};
                {error, {{EL,_},M,D},{L,_}} -> {error, {EL,M,D},L}
            end,
            {done, Ret1, R}
    end.

do_token([], Chars, Line, Col) ->
    token(yystate(), Chars, Line, Col, Chars, 0, Line, Col, reject, 0);
do_token({token,State,Line,Col,Tcs,Tlen,Tline,Tcol,Action,Alen}, Chars, _, _) ->
    token(State, Chars, Line, Col, Tcs ++ Chars, Tlen, Tline, Tcol, Action, Alen).

%% token(State, InChars, Line, Col, TokenChars, TokenLen, TokenLine, TokenCol
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, C0, Tcs, Tlen0, Tline, Tcol, A0, Alen0) ->
    case yystate(S0, Ics0, L0, C0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1,C1} ->
            C2 = adjust_col(Tcs, Alen1, C1),
            token_cont(Ics1, L1, C2, yyaction(A1, Alen1, Tcs, Tline,Tcol));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,C1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,C1,Tcs,Alen1,Tline,Tcol,A1,Alen1}};
        {A1,Alen1,Ics1,L1,C1,_S1} ->               % Take what we got
            C2 = adjust_col(Tcs, Alen1, C1),
            token_cont(Ics1, L1, C2, yyaction(A1, Alen1, Tcs, Tline,Tcol));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,C1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,C1,Tcs,Tlen1,Tline,Tcol,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,C1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{{Tline,Tcol},?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},{L1,C1}};
                     true -> {eof,{L1,C1}}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,_L1,_C1,_S1} ->    % No token match
            Error = {{Tline,Tcol},?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,{Tline,Tcol}},Ics1};
        {A1,Alen1,Tlen1,_Ics1,L1,_C1,_S1} ->       % Use last accept match
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            C2 = C0 + Alen1,
            token_cont(Tcs1, L2, C2, yyaction(A1, Alen1, Tcs, Tline, Tcol))
    end.

%% token_cont(RestChars, Line, Col, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

-dialyzer({nowarn_function, token_cont/4}).

token_cont(Rest, Line, Col, {token,T}) ->
    {done,{ok,T,{Line,Col}},Rest};
token_cont(Rest, Line, Col, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,{Line,Col}},NewRest};
token_cont(Rest, Line, Col, {end_token,T}) ->
    {done,{ok,T,{Line,Col}},Rest};
token_cont(Rest, Line, Col, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,{Line,Col}},NewRest};
token_cont(Rest, Line, Col, skip_token) ->
    token(yystate(), Rest, Line, Col, Rest, 0, Line, Col, reject, 0);
token_cont(Rest, Line, Col, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, Col, NewRest, 0, Line, Col, reject, 0);
token_cont(Rest, Line, Col, {error,S}) ->
    {done,{error,{{Line, Col},?MODULE,{user,S}},{Line, Col}},Rest}.

%% tokens(Continuation, Chars) ->
%% tokens(Continuation, Chars, Loc) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,CurrCol,TokenChars,TokenLen,TokenLine,TokenCur,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,CurrCol,TokenChars,TokenLen,TokenLine,TokenCur,Error,AccAction,AccLen}

tokens(Cont,Chars) -> 
    tokens(Cont,Chars,1).
tokens(Cont, Chars, Line) -> 
    case do_tokens(Cont,Chars,Line,1) of
        {more, _} = C -> C;
        {done, Ret0, R} ->
            Ret1 = case Ret0 of
                {ok, T, {L,_}} -> {ok, T, L};
                {eof, {L,_}} -> {eof, L};
                {error, {{EL,_},M,D},{L,_}} -> {error, {EL,M,D},L}
            end,
            {done, Ret1, R}
    end.

do_tokens([], Chars, Line, Col) ->
    tokens(yystate(), Chars, Line, Col, Chars, 0, Line, Col, [], reject, 0);
do_tokens({tokens,State,Line,Col,Tcs,Tlen,Tline,Tcol,Ts,Action,Alen}, Chars, _,_) ->
    tokens(State, Chars, Line, Col, Tcs ++ Chars, Tlen, Tline, Tcol, Ts, Action, Alen);
do_tokens({skip_tokens,State,Line, Col, Tcs,Tlen,Tline,Tcol,Error,Action,Alen}, Chars, _,_) ->
    skip_tokens(State, Chars, Line, Col, Tcs ++ Chars, Tlen, Tline, Tcol, Error, Action, Alen).

%% tokens(State, InChars, Line, Col, TokenChars, TokenLen, TokenLine, TokenCol,Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, C0, Tcs, Tlen0, Tline, Tcol, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, C0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1,C1} ->
            C2 = adjust_col(Tcs, Alen1, C1),
            tokens_cont(Ics1, L1, C2, yyaction(A1, Alen1, Tcs, Tline, Tcol), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,C1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,C1,Tcs,Alen1,Tline,Tcol,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,C1,_S1} ->               % Take what we got
            C2 = adjust_col(Tcs, Alen1, C1),
            tokens_cont(Ics1, L1, C2, yyaction(A1, Alen1, Tcs, Tline,Tcol), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,C1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,C1,Tcs,Tlen1,Tline,Tcol,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,C1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{{Tline,Tcol},?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},{L1,C1}};
                     Ts == [] -> {eof,{L1,C1}};
                     true -> {ok,yyrev(Ts),{L1,C1}}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,C1,_S1} ->
            %% Skip rest of tokens.
            Error = {{L1,C1},?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, C1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_C1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline,Tcol),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            C2 = C0 + Alen1,
            tokens_cont(Tcs1, L2, C2, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Column, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

-dialyzer({nowarn_function, tokens_cont/5}).

tokens_cont(Rest, Line, Col, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Col, Rest, 0, Line, Col, [T|Ts], reject, 0);
tokens_cont(Rest, Line, Col, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, Col, NewRest, 0, Line, Col, [T|Ts], reject, 0);
tokens_cont(Rest, Line, Col, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),{Line,Col}},Rest};
tokens_cont(Rest, Line, Col, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),{Line, Col}},NewRest};
tokens_cont(Rest, Line, Col, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Col, Rest, 0, Line, Col, Ts, reject, 0);
tokens_cont(Rest, Line, Col, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, Col, NewRest, 0, Line, Col, Ts, reject, 0);
tokens_cont(Rest, Line, Col, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, Col, {{Line,Col},?MODULE,{user,S}}).

%% skip_tokens(InChars, Line, Col, Error) -> {done,{error,Error,{Line,Col}},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Col, Error) ->
    skip_tokens(yystate(), Ics, Line, Col, Ics, 0, Line, Col, Error, reject, 0).

%% skip_tokens(State, InChars, Line, Col, TokenChars, TokenLen, TokenLine, TokenCol, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, C0, Tcs, Tlen0, Tline, Tcol, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, C0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1, C1} ->                  % Accepting end state
            skip_cont(Ics1, L1, C1, yyaction(A1, Alen1, Tcs, Tline, Tcol), Error);
        {A1,Alen1,[],L1,C1, S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,C1,Tcs,Alen1,Tline,Tcol,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,C1,_S1} ->
            skip_cont(Ics1, L1, C1, yyaction(A1, Alen1, Tcs, Tline, Tcol), Error);
        {A1,Alen1,Tlen1,[],L1,C1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,C1,Tcs,Tlen1,Tline,Tcol,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,C1,_S1} ->
            {done,{error,Error,{L1,C1}},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,C1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, C1,Error);
        {A1,Alen1,Tlen1,_Ics1,L1,C1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline, Tcol),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            skip_cont(Tcs1, L2, C1, Token, Error)
    end.

%% skip_cont(RestChars, Line, Col, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

-dialyzer({nowarn_function, skip_cont/5}).

skip_cont(Rest, Line, Col, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Col, Rest, 0, Line, Col, Error, reject, 0);
skip_cont(Rest, Line, Col, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, Col, NewRest, 0, Line, Col, Error, reject, 0);
skip_cont(Rest, Line, Col, {end_token,_T}, Error) ->
    {done,{error,Error,{Line,Col}},Rest};
skip_cont(Rest, Line, Col, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,{Line,Col}},NewRest};
skip_cont(Rest, Line, Col, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Col, Rest, 0, Line, Col, Error, reject, 0);
skip_cont(Rest, Line, Col, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, Col, NewRest, 0, Line, Col, Error, reject, 0);
skip_cont(Rest, Line, Col, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Col, Rest, 0, Line, Col, Error, reject, 0).

-compile({nowarn_unused_function, [yyrev/1, yyrev/2, yypre/2, yysuf/2]}).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% adjust_line(TokenLength, AcceptLength, Chars, Line) -> NewLine
%% Make sure that newlines in Chars are not counted twice.
%% Line has been updated with respect to newlines in the prefix of
%% Chars consisting of (TokenLength - AcceptLength) characters.

-compile({nowarn_unused_function, adjust_line/4}).

adjust_line(N, N, _Cs, L) -> L;
adjust_line(T, A, [$\n|Cs], L) ->
    adjust_line(T-1, A, Cs, L-1);
adjust_line(T, A, [_|Cs], L) ->
    adjust_line(T-1, A, Cs, L).

%% adjust_col(Chars, AcceptLength, Col) -> NewCol
%% Handle newlines, tabs and unicode chars.
adjust_col(_, 0, Col) ->
    Col;
adjust_col([$\n | R], L, _) ->
    adjust_col(R, L-1, 1);
adjust_col([$\t | R], L, Col) ->
    adjust_col(R, L-1, tab_forward(Col)+1);
adjust_col([C | R], L, Col) when C>=0 andalso C=< 16#7F ->
    adjust_col(R, L-1, Col+1);
adjust_col([C | R], L, Col) when C>= 16#80 andalso C=< 16#7FF ->
    adjust_col(R, L-1, Col+2);
adjust_col([C | R], L, Col) when C>= 16#800 andalso C=< 16#FFFF ->
    adjust_col(R, L-1, Col+3);
adjust_col([C | R], L, Col) when C>= 16#10000 andalso C=< 16#10FFFF ->
    adjust_col(R, L-1, Col+4).

tab_forward(C) ->
    D = C rem tab_size(),
    A = tab_size()-D,
    C+A.

tab_size() -> 8.

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, Col, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line, Col} |
%% {Action, AcceptLen, RestChars, Line, Col, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, Col, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, Col, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("src/lx_lexer.erl", 381).
yystate() -> 108.

yystate(111, [110|Ics], Line, Col, Tlen, _, _) ->
    yystate(109, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(111, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(111, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(111, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(111, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(111, [C|Ics], Line, Col, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(111, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,111};
yystate(110, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(110, Ics, Line, Col, Tlen+1, 44, Tlen);
yystate(110, [9|Ics], Line, Col, Tlen, _, _) ->
    yystate(110, Ics, Line, Col, Tlen+1, 44, Tlen);
yystate(110, Ics, Line, Col, Tlen, _, _) ->
    {44,Tlen,Ics,Line,Col,110};
yystate(109, [100|Ics], Line, Col, Tlen, _, _) ->
    yystate(105, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(109, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(109, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(109, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(109, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 99 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(109, [C|Ics], Line, Col, Tlen, _, _) when C >= 101, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(109, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,109};
yystate(108, [125|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(104, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(108, [123|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(100, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(108, [116|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(80, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(108, [115|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(44, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(108, [110|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(20, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(108, [109|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(48, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(108, [108|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(11, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(108, [106|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(48, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(108, [107|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(48, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(108, [105|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(27, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(108, [103|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(48, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(108, [104|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(48, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(108, [102|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(108, [101|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(111, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(108, [100|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(101, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(108, [99|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(48, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(108, [98|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(65, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(108, [97|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(37, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(108, [95|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(108, [93|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(108, [91|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(108, [61|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(1, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(108, [59|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(2, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(108, [58|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(6, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(108, [47|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(42, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(108, [45|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(46, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(108, [44|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(50, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(108, [43|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(54, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(108, [42|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(62, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(108, [41|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(66, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(108, [40|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(70, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(108, [39|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(74, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(108, [35|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(90, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(108, [34|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(98, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(108, [32|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(110, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(108, [13|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(102, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(108, [10|Ics], Line, _, Tlen, Action, Alen) ->
    yystate(106, Ics, Line+1, 1, Tlen+1, Action, Alen);
yystate(108, [9|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(110, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(108, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(30, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(108, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(108, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 111, C =< 114 ->
    yystate(48, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(108, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 117, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(108, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,108};
yystate(107, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 6, Tlen);
yystate(107, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 6, Tlen);
yystate(107, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 6, Tlen);
yystate(107, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 6, Tlen);
yystate(107, Ics, Line, Col, Tlen, _, _) ->
    {6,Tlen,Ics,Line,Col,107};
yystate(106, Ics, Line, Col, Tlen, _, _) ->
    {45,Tlen,Ics,Line,Col};
yystate(105, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 11, Tlen);
yystate(105, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 11, Tlen);
yystate(105, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 11, Tlen);
yystate(105, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 11, Tlen);
yystate(105, Ics, Line, Col, Tlen, _, _) ->
    {11,Tlen,Ics,Line,Col,105};
yystate(104, Ics, Line, Col, Tlen, _, _) ->
    {34,Tlen,Ics,Line,Col};
yystate(103, [101|Ics], Line, Col, Tlen, _, _) ->
    yystate(107, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(103, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(103, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(103, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(103, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(103, [C|Ics], Line, Col, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(103, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,103};
yystate(102, [10|Ics], Line, _, Tlen, _, _) ->
    yystate(106, Ics, Line+1, 1, Tlen+1, 45, Tlen);
yystate(102, Ics, Line, Col, Tlen, _, _) ->
    {45,Tlen,Ics,Line,Col,102};
yystate(101, [111|Ics], Line, Col, Tlen, _, _) ->
    yystate(97, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(101, [101|Ics], Line, Col, Tlen, _, _) ->
    yystate(93, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(101, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(101, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(101, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(101, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(101, [C|Ics], Line, Col, Tlen, _, _) when C >= 102, C =< 110 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(101, [C|Ics], Line, Col, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(101, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,101};
yystate(100, [65|Ics], Line, Col, Tlen, _, _) ->
    yystate(96, Ics, Line, Col, Tlen+1, 33, Tlen);
yystate(100, Ics, Line, Col, Tlen, _, _) ->
    {33,Tlen,Ics,Line,Col,100};
yystate(99, [115|Ics], Line, Col, Tlen, _, _) ->
    yystate(103, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(99, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(99, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(99, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(99, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(99, [C|Ics], Line, Col, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(99, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,99};
yystate(98, [34|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(94, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(98, [10|Ics], Line, _, Tlen, Action, Alen) ->
    yystate(98, Ics, Line+1, 1, Tlen+1, Action, Alen);
yystate(98, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(98, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(98, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(98, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(98, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 35 ->
    yystate(98, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(98, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,98};
yystate(97, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(97, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(97, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(97, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(97, Ics, Line, Col, Tlen, _, _) ->
    {10,Tlen,Ics,Line,Col,97};
yystate(96, [45|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(92, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(96, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,96};
yystate(95, [108|Ics], Line, Col, Tlen, _, _) ->
    yystate(99, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(95, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(95, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(95, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(95, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(95, [C|Ics], Line, Col, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(95, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,95};
yystate(94, Ics, Line, Col, Tlen, _, _) ->
    {3,Tlen,Ics,Line,Col};
yystate(93, [102|Ics], Line, Col, Tlen, _, _) ->
    yystate(89, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(93, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(93, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(93, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(93, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 101 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(93, [C|Ics], Line, Col, Tlen, _, _) when C >= 103, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(93, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,93};
yystate(92, [90|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(88, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(92, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,92};
yystate(91, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 16, Tlen);
yystate(91, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 16, Tlen);
yystate(91, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 16, Tlen);
yystate(91, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 16, Tlen);
yystate(91, Ics, Line, Col, Tlen, _, _) ->
    {16,Tlen,Ics,Line,Col,91};
yystate(90, [C|Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(90, Ics, Line, Col, Tlen+1, 46, Tlen);
yystate(90, [C|Ics], Line, Col, Tlen, _, _) when C >= 11 ->
    yystate(90, Ics, Line, Col, Tlen+1, 46, Tlen);
yystate(90, Ics, Line, Col, Tlen, _, _) ->
    {46,Tlen,Ics,Line,Col,90};
yystate(89, [109|Ics], Line, Col, Tlen, _, _) ->
    yystate(85, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(89, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(89, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(89, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(89, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 108 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(89, [C|Ics], Line, Col, Tlen, _, _) when C >= 110, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(89, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,89};
yystate(88, [125|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(84, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(88, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,88};
yystate(87, [116|Ics], Line, Col, Tlen, _, _) ->
    yystate(91, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(87, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(87, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(87, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(87, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(87, [C|Ics], Line, Col, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(87, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,87};
yystate(86, Ics, Line, Col, Tlen, _, _) ->
    {12,Tlen,Ics,Line,Col};
yystate(85, [97|Ics], Line, Col, Tlen, _, _) ->
    yystate(81, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(85, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(85, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(85, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(85, [C|Ics], Line, Col, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(85, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,85};
yystate(84, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(84, Ics, Line, Col, Tlen+1, 14, Tlen);
yystate(84, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(84, Ics, Line, Col, Tlen+1, 14, Tlen);
yystate(84, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(84, Ics, Line, Col, Tlen+1, 14, Tlen);
yystate(84, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(84, Ics, Line, Col, Tlen+1, 14, Tlen);
yystate(84, Ics, Line, Col, Tlen, _, _) ->
    {14,Tlen,Ics,Line,Col,84};
yystate(83, [97|Ics], Line, Col, Tlen, _, _) ->
    yystate(87, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(83, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(83, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(83, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(83, [C|Ics], Line, Col, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(83, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,83};
yystate(82, [39|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(86, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(82, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,82};
yystate(81, [99|Ics], Line, Col, Tlen, _, _) ->
    yystate(77, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(81, [97|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(81, [98|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(81, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(81, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(81, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(81, [C|Ics], Line, Col, Tlen, _, _) when C >= 100, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(81, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,81};
yystate(80, [117|Ics], Line, Col, Tlen, _, _) ->
    yystate(76, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(80, [115|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(80, [116|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(80, [114|Ics], Line, Col, Tlen, _, _) ->
    yystate(60, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(80, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(80, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(80, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(80, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(80, [C|Ics], Line, Col, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(80, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,80};
yystate(79, [111|Ics], Line, Col, Tlen, _, _) ->
    yystate(83, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(79, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(79, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(79, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(79, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(79, [C|Ics], Line, Col, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(79, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,79};
yystate(78, [62|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(82, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(78, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,78};
yystate(77, [114|Ics], Line, Col, Tlen, _, _) ->
    yystate(73, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(77, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(77, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(77, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(77, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(77, [C|Ics], Line, Col, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(77, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,77};
yystate(76, [112|Ics], Line, Col, Tlen, _, _) ->
    yystate(72, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(76, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(76, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(76, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(76, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 111 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(76, [C|Ics], Line, Col, Tlen, _, _) when C >= 113, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(76, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,76};
yystate(75, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 21, Tlen);
yystate(75, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 21, Tlen);
yystate(75, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 21, Tlen);
yystate(75, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 21, Tlen);
yystate(75, Ics, Line, Col, Tlen, _, _) ->
    {21,Tlen,Ics,Line,Col,75};
yystate(74, [45|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(78, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(74, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,74};
yystate(73, [111|Ics], Line, Col, Tlen, _, _) ->
    yystate(69, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(73, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(73, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(73, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(73, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(73, [C|Ics], Line, Col, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(73, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,73};
yystate(72, [108|Ics], Line, Col, Tlen, _, _) ->
    yystate(68, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(72, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(72, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(72, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(72, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(72, [C|Ics], Line, Col, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(72, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,72};
yystate(71, [110|Ics], Line, Col, Tlen, _, _) ->
    yystate(75, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(71, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(71, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(71, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(71, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(71, [C|Ics], Line, Col, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(71, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,71};
yystate(70, Ics, Line, Col, Tlen, _, _) ->
    {29,Tlen,Ics,Line,Col};
yystate(69, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(69, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(69, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(69, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(69, Ics, Line, Col, Tlen, _, _) ->
    {8,Tlen,Ics,Line,Col,69};
yystate(68, [101|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(68, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(68, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(68, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(68, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(68, [C|Ics], Line, Col, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(68, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,68};
yystate(67, [117|Ics], Line, Col, Tlen, _, _) ->
    yystate(71, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(67, [108|Ics], Line, Col, Tlen, _, _) ->
    yystate(79, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(67, [97|Ics], Line, Col, Tlen, _, _) ->
    yystate(95, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(67, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(67, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(67, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(67, [C|Ics], Line, Col, Tlen, _, _) when C >= 98, C =< 107 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(67, [C|Ics], Line, Col, Tlen, _, _) when C >= 109, C =< 116 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(67, [C|Ics], Line, Col, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(67, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,67};
yystate(66, Ics, Line, Col, Tlen, _, _) ->
    {30,Tlen,Ics,Line,Col};
yystate(65, [111|Ics], Line, Col, Tlen, _, _) ->
    yystate(61, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(65, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(65, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(65, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(65, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(65, [C|Ics], Line, Col, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(65, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,65};
yystate(64, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 23, Tlen);
yystate(64, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 23, Tlen);
yystate(64, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 23, Tlen);
yystate(64, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 23, Tlen);
yystate(64, Ics, Line, Col, Tlen, _, _) ->
    {23,Tlen,Ics,Line,Col,64};
yystate(63, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 9, Tlen);
yystate(63, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 9, Tlen);
yystate(63, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 9, Tlen);
yystate(63, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 9, Tlen);
yystate(63, Ics, Line, Col, Tlen, _, _) ->
    {9,Tlen,Ics,Line,Col,63};
yystate(62, Ics, Line, Col, Tlen, _, _) ->
    {39,Tlen,Ics,Line,Col};
yystate(61, [111|Ics], Line, Col, Tlen, _, _) ->
    yystate(57, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(61, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(61, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(61, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(61, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(61, [C|Ics], Line, Col, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(61, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,61};
yystate(60, [117|Ics], Line, Col, Tlen, _, _) ->
    yystate(56, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(60, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(60, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(60, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(60, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(60, [C|Ics], Line, Col, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(60, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,60};
yystate(59, [121|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(59, [122|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(59, [120|Ics], Line, Col, Tlen, _, _) ->
    yystate(63, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(59, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(59, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(59, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(59, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 119 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(59, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,59};
yystate(58, Ics, Line, Col, Tlen, _, _) ->
    {41,Tlen,Ics,Line,Col};
yystate(57, [108|Ics], Line, Col, Tlen, _, _) ->
    yystate(53, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(57, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(57, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(57, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(57, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(57, [C|Ics], Line, Col, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(57, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,57};
yystate(56, [101|Ics], Line, Col, Tlen, _, _) ->
    yystate(52, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(56, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(56, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(56, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(56, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(56, [C|Ics], Line, Col, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(56, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,56};
yystate(55, [105|Ics], Line, Col, Tlen, _, _) ->
    yystate(59, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(55, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(55, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(55, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(55, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(55, [C|Ics], Line, Col, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(55, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,55};
yystate(54, [43|Ics], Line, Col, Tlen, _, _) ->
    yystate(58, Ics, Line, Col, Tlen+1, 37, Tlen);
yystate(54, Ics, Line, Col, Tlen, _, _) ->
    {37,Tlen,Ics,Line,Col,54};
yystate(53, [101|Ics], Line, Col, Tlen, _, _) ->
    yystate(49, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(53, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(53, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(53, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(53, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(53, [C|Ics], Line, Col, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(53, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,53};
yystate(52, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 5, Tlen);
yystate(52, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 5, Tlen);
yystate(52, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 5, Tlen);
yystate(52, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 5, Tlen);
yystate(52, Ics, Line, Col, Tlen, _, _) ->
    {5,Tlen,Ics,Line,Col,52};
yystate(51, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 15, Tlen);
yystate(51, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 15, Tlen);
yystate(51, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 15, Tlen);
yystate(51, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 15, Tlen);
yystate(51, Ics, Line, Col, Tlen, _, _) ->
    {15,Tlen,Ics,Line,Col,51};
yystate(50, Ics, Line, Col, Tlen, _, _) ->
    {35,Tlen,Ics,Line,Col};
yystate(49, [97|Ics], Line, Col, Tlen, _, _) ->
    yystate(45, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(49, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(49, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(49, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(49, [C|Ics], Line, Col, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(49, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,49};
yystate(48, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(48, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(48, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(48, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(48, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,48};
yystate(47, [114|Ics], Line, Col, Tlen, _, _) ->
    yystate(51, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(47, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(47, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(47, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(47, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(47, [C|Ics], Line, Col, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(47, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,47};
yystate(46, Ics, Line, Col, Tlen, _, _) ->
    {38,Tlen,Ics,Line,Col};
yystate(45, [110|Ics], Line, Col, Tlen, _, _) ->
    yystate(41, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(45, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(45, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(45, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(45, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(45, [C|Ics], Line, Col, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(45, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,45};
yystate(44, [116|Ics], Line, Col, Tlen, _, _) ->
    yystate(40, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(44, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(44, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(44, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(44, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(44, [C|Ics], Line, Col, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(44, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,44};
yystate(43, [101|Ics], Line, Col, Tlen, _, _) ->
    yystate(47, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(43, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(43, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(43, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(43, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(43, [C|Ics], Line, Col, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(43, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,43};
yystate(42, Ics, Line, Col, Tlen, _, _) ->
    {40,Tlen,Ics,Line,Col};
yystate(41, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 18, Tlen);
yystate(41, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 18, Tlen);
yystate(41, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 18, Tlen);
yystate(41, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 18, Tlen);
yystate(41, Ics, Line, Col, Tlen, _, _) ->
    {18,Tlen,Ics,Line,Col,41};
yystate(40, [114|Ics], Line, Col, Tlen, _, _) ->
    yystate(36, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(40, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(40, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(40, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(40, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(40, [C|Ics], Line, Col, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(40, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,40};
yystate(39, [103|Ics], Line, Col, Tlen, _, _) ->
    yystate(43, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(39, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(39, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(39, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(39, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(39, [C|Ics], Line, Col, Tlen, _, _) when C >= 104, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(39, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,39};
yystate(38, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(38, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(38, Ics, Line, Col, Tlen, _, _) ->
    {2,Tlen,Ics,Line,Col,38};
yystate(37, [116|Ics], Line, Col, Tlen, _, _) ->
    yystate(33, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(37, [110|Ics], Line, Col, Tlen, _, _) ->
    yystate(21, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(37, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(37, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(37, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(37, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(37, [C|Ics], Line, Col, Tlen, _, _) when C >= 111, C =< 115 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(37, [C|Ics], Line, Col, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(37, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,37};
yystate(36, [105|Ics], Line, Col, Tlen, _, _) ->
    yystate(32, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(36, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(36, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(36, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(36, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(36, [C|Ics], Line, Col, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(36, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,36};
yystate(35, [101|Ics], Line, Col, Tlen, _, _) ->
    yystate(39, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(35, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(35, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(35, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(35, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(35, [C|Ics], Line, Col, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(35, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,35};
yystate(34, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(38, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(34, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,34};
yystate(33, [111|Ics], Line, Col, Tlen, _, _) ->
    yystate(29, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(33, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(33, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(33, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(33, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(33, [C|Ics], Line, Col, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(33, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,33};
yystate(32, [110|Ics], Line, Col, Tlen, _, _) ->
    yystate(28, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(32, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(32, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(32, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(32, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(32, [C|Ics], Line, Col, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(32, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,32};
yystate(31, [116|Ics], Line, Col, Tlen, _, _) ->
    yystate(35, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(31, [102|Ics], Line, Col, Tlen, _, _) ->
    yystate(55, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(31, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(31, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(31, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(31, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 101 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(31, [C|Ics], Line, Col, Tlen, _, _) when C >= 103, C =< 115 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(31, [C|Ics], Line, Col, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(31, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,31};
yystate(30, [46|Ics], Line, Col, Tlen, _, _) ->
    yystate(34, Ics, Line, Col, Tlen+1, 1, Tlen);
yystate(30, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(30, Ics, Line, Col, Tlen+1, 1, Tlen);
yystate(30, Ics, Line, Col, Tlen, _, _) ->
    {1,Tlen,Ics,Line,Col,30};
yystate(29, [109|Ics], Line, Col, Tlen, _, _) ->
    yystate(25, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(29, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(29, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(29, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(29, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 108 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(29, [C|Ics], Line, Col, Tlen, _, _) when C >= 110, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(29, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,29};
yystate(28, [103|Ics], Line, Col, Tlen, _, _) ->
    yystate(24, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(28, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(28, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(28, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(28, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(28, [C|Ics], Line, Col, Tlen, _, _) when C >= 104, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(28, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,28};
yystate(27, [110|Ics], Line, Col, Tlen, _, _) ->
    yystate(31, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(27, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(27, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(27, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(27, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(27, [C|Ics], Line, Col, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(27, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,27};
yystate(26, Ics, Line, Col, Tlen, _, _) ->
    {0,Tlen,Ics,Line,Col};
yystate(25, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 19, Tlen);
yystate(25, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 19, Tlen);
yystate(25, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 19, Tlen);
yystate(25, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 19, Tlen);
yystate(25, Ics, Line, Col, Tlen, _, _) ->
    {19,Tlen,Ics,Line,Col,25};
yystate(24, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 17, Tlen);
yystate(24, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 17, Tlen);
yystate(24, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 17, Tlen);
yystate(24, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 17, Tlen);
yystate(24, Ics, Line, Col, Tlen, _, _) ->
    {17,Tlen,Ics,Line,Col,24};
yystate(23, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 22, Tlen);
yystate(23, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 22, Tlen);
yystate(23, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 22, Tlen);
yystate(23, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 22, Tlen);
yystate(23, Ics, Line, Col, Tlen, _, _) ->
    {22,Tlen,Ics,Line,Col,23};
yystate(22, [39|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(26, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(22, [10|Ics], Line, _, Tlen, Action, Alen) ->
    yystate(22, Ics, Line+1, 1, Tlen+1, Action, Alen);
yystate(22, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(22, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(22, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(22, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(22, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 40 ->
    yystate(22, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(22, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,22};
yystate(21, [122|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(21, [121|Ics], Line, Col, Tlen, _, _) ->
    yystate(17, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(21, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(21, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(21, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(21, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 120 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(21, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,21};
yystate(20, [117|Ics], Line, Col, Tlen, _, _) ->
    yystate(16, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(20, [105|Ics], Line, Col, Tlen, _, _) ->
    yystate(3, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(20, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(20, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(20, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(20, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(20, [C|Ics], Line, Col, Tlen, _, _) when C >= 106, C =< 116 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(20, [C|Ics], Line, Col, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(20, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,20};
yystate(19, [116|Ics], Line, Col, Tlen, _, _) ->
    yystate(23, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(19, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(19, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(19, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(19, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(19, [C|Ics], Line, Col, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(19, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,19};
yystate(18, [10|Ics], Line, _, Tlen, Action, Alen) ->
    yystate(22, Ics, Line+1, 1, Tlen+1, Action, Alen);
yystate(18, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(22, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(18, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(22, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(18, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 40 ->
    yystate(22, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(18, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,18};
yystate(17, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 20, Tlen);
yystate(17, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 20, Tlen);
yystate(17, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 20, Tlen);
yystate(17, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 20, Tlen);
yystate(17, Ics, Line, Col, Tlen, _, _) ->
    {20,Tlen,Ics,Line,Col,17};
yystate(16, [109|Ics], Line, Col, Tlen, _, _) ->
    yystate(12, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(16, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(16, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(16, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(16, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 108 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(16, [C|Ics], Line, Col, Tlen, _, _) when C >= 110, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(16, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,16};
yystate(15, [115|Ics], Line, Col, Tlen, _, _) ->
    yystate(19, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(15, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(15, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(15, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(15, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(15, [C|Ics], Line, Col, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(15, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,15};
yystate(14, Ics, Line, Col, Tlen, _, _) ->
    {13,Tlen,Ics,Line,Col};
yystate(13, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 25, Tlen);
yystate(13, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 25, Tlen);
yystate(13, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 25, Tlen);
yystate(13, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 25, Tlen);
yystate(13, Ics, Line, Col, Tlen, _, _) ->
    {25,Tlen,Ics,Line,Col,13};
yystate(12, [98|Ics], Line, Col, Tlen, _, _) ->
    yystate(8, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(12, [97|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(12, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(12, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(12, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(12, [C|Ics], Line, Col, Tlen, _, _) when C >= 99, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(12, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,12};
yystate(11, [105|Ics], Line, Col, Tlen, _, _) ->
    yystate(15, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(11, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(11, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(11, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(11, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(11, [C|Ics], Line, Col, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(11, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,11};
yystate(10, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(10, Ics, Line, Col, Tlen+1, 4, Tlen);
yystate(10, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(10, Ics, Line, Col, Tlen+1, 4, Tlen);
yystate(10, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(10, Ics, Line, Col, Tlen+1, 4, Tlen);
yystate(10, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(10, Ics, Line, Col, Tlen+1, 4, Tlen);
yystate(10, Ics, Line, Col, Tlen, _, _) ->
    {4,Tlen,Ics,Line,Col,10};
yystate(9, Ics, Line, Col, Tlen, _, _) ->
    {32,Tlen,Ics,Line,Col};
yystate(8, [101|Ics], Line, Col, Tlen, _, _) ->
    yystate(4, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(8, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(8, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(8, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(8, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(8, [C|Ics], Line, Col, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(8, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,8};
yystate(7, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(7, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(7, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(7, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(7, Ics, Line, Col, Tlen, _, _) ->
    {7,Tlen,Ics,Line,Col,7};
yystate(6, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(10, Ics, Line, Col, Tlen+1, 36, Tlen);
yystate(6, [58|Ics], Line, Col, Tlen, _, _) ->
    yystate(14, Ics, Line, Col, Tlen+1, 36, Tlen);
yystate(6, [39|Ics], Line, Col, Tlen, _, _) ->
    yystate(18, Ics, Line, Col, Tlen+1, 36, Tlen);
yystate(6, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(10, Ics, Line, Col, Tlen+1, 36, Tlen);
yystate(6, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(10, Ics, Line, Col, Tlen+1, 36, Tlen);
yystate(6, Ics, Line, Col, Tlen, _, _) ->
    {36,Tlen,Ics,Line,Col,6};
yystate(5, Ics, Line, Col, Tlen, _, _) ->
    {31,Tlen,Ics,Line,Col};
yystate(4, [114|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(4, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(4, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(4, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(4, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(4, [C|Ics], Line, Col, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(4, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,4};
yystate(3, [108|Ics], Line, Col, Tlen, _, _) ->
    yystate(7, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(3, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(3, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(3, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(3, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(3, [C|Ics], Line, Col, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(3, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,3};
yystate(2, Ics, Line, Col, Tlen, _, _) ->
    {28,Tlen,Ics,Line,Col};
yystate(1, Ics, Line, Col, Tlen, _, _) ->
    {27,Tlen,Ics,Line,Col};
yystate(0, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 24, Tlen);
yystate(0, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Col, Tlen+1, 24, Tlen);
yystate(0, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(48, Ics, Line, Col, Tlen+1, 24, Tlen);
yystate(0, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(48, Ics, Line, Col, Tlen+1, 24, Tlen);
yystate(0, Ics, Line, Col, Tlen, _, _) ->
    {24,Tlen,Ics,Line,Col,0};
yystate(S, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine, TokenCol) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, TokenLen, YYtcs, TokenLine, TokenCol) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_0(TokenChars, TokenLine, TokenCol);
yyaction(1, TokenLen, YYtcs, TokenLine, TokenCol) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_1(TokenChars, TokenLine, TokenCol);
yyaction(2, TokenLen, YYtcs, TokenLine, TokenCol) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_2(TokenChars, TokenLine, TokenCol);
yyaction(3, TokenLen, YYtcs, TokenLine, TokenCol) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_3(TokenChars, TokenLine, TokenCol);
yyaction(4, TokenLen, YYtcs, TokenLine, TokenCol) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_4(TokenChars, TokenLine, TokenCol);
yyaction(5, _, _, TokenLine, TokenCol) ->
    yyaction_5(TokenLine, TokenCol);
yyaction(6, _, _, TokenLine, TokenCol) ->
    yyaction_6(TokenLine, TokenCol);
yyaction(7, _, _, TokenLine, TokenCol) ->
    yyaction_7(TokenLine, TokenCol);
yyaction(8, _, _, TokenLine, TokenCol) ->
    yyaction_8(TokenLine, TokenCol);
yyaction(9, _, _, TokenLine, TokenCol) ->
    yyaction_9(TokenLine, TokenCol);
yyaction(10, _, _, TokenLine, TokenCol) ->
    yyaction_10(TokenLine, TokenCol);
yyaction(11, _, _, TokenLine, TokenCol) ->
    yyaction_11(TokenLine, TokenCol);
yyaction(12, _, _, TokenLine, TokenCol) ->
    yyaction_12(TokenLine, TokenCol);
yyaction(13, _, _, TokenLine, TokenCol) ->
    yyaction_13(TokenLine, TokenCol);
yyaction(14, TokenLen, YYtcs, TokenLine, TokenCol) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_14(TokenChars, TokenLine, TokenCol);
yyaction(15, _, _, TokenLine, TokenCol) ->
    yyaction_15(TokenLine, TokenCol);
yyaction(16, _, _, TokenLine, TokenCol) ->
    yyaction_16(TokenLine, TokenCol);
yyaction(17, _, _, TokenLine, TokenCol) ->
    yyaction_17(TokenLine, TokenCol);
yyaction(18, _, _, TokenLine, TokenCol) ->
    yyaction_18(TokenLine, TokenCol);
yyaction(19, _, _, TokenLine, TokenCol) ->
    yyaction_19(TokenLine, TokenCol);
yyaction(20, _, _, TokenLine, TokenCol) ->
    yyaction_20(TokenLine, TokenCol);
yyaction(21, _, _, TokenLine, TokenCol) ->
    yyaction_21(TokenLine, TokenCol);
yyaction(22, _, _, TokenLine, TokenCol) ->
    yyaction_22(TokenLine, TokenCol);
yyaction(23, _, _, TokenLine, TokenCol) ->
    yyaction_23(TokenLine, TokenCol);
yyaction(24, _, _, TokenLine, TokenCol) ->
    yyaction_24(TokenLine, TokenCol);
yyaction(25, _, _, TokenLine, TokenCol) ->
    yyaction_25(TokenLine, TokenCol);
yyaction(26, TokenLen, YYtcs, TokenLine, TokenCol) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_26(TokenChars, TokenLine, TokenCol);
yyaction(27, _, _, TokenLine, TokenCol) ->
    yyaction_27(TokenLine, TokenCol);
yyaction(28, _, _, TokenLine, TokenCol) ->
    yyaction_28(TokenLine, TokenCol);
yyaction(29, _, _, TokenLine, TokenCol) ->
    yyaction_29(TokenLine, TokenCol);
yyaction(30, _, _, TokenLine, TokenCol) ->
    yyaction_30(TokenLine, TokenCol);
yyaction(31, _, _, TokenLine, TokenCol) ->
    yyaction_31(TokenLine, TokenCol);
yyaction(32, _, _, TokenLine, TokenCol) ->
    yyaction_32(TokenLine, TokenCol);
yyaction(33, _, _, TokenLine, TokenCol) ->
    yyaction_33(TokenLine, TokenCol);
yyaction(34, _, _, TokenLine, TokenCol) ->
    yyaction_34(TokenLine, TokenCol);
yyaction(35, _, _, TokenLine, TokenCol) ->
    yyaction_35(TokenLine, TokenCol);
yyaction(36, _, _, TokenLine, TokenCol) ->
    yyaction_36(TokenLine, TokenCol);
yyaction(37, _, _, TokenLine, TokenCol) ->
    yyaction_37(TokenLine, TokenCol);
yyaction(38, _, _, TokenLine, TokenCol) ->
    yyaction_38(TokenLine, TokenCol);
yyaction(39, _, _, TokenLine, TokenCol) ->
    yyaction_39(TokenLine, TokenCol);
yyaction(40, _, _, TokenLine, TokenCol) ->
    yyaction_40(TokenLine, TokenCol);
yyaction(41, _, _, TokenLine, TokenCol) ->
    yyaction_41(TokenLine, TokenCol);
yyaction(42, _, _, TokenLine, TokenCol) ->
    yyaction_42(TokenLine, TokenCol);
yyaction(43, _, _, TokenLine, TokenCol) ->
    yyaction_43(TokenLine, TokenCol);
yyaction(44, _, _, _, _) ->
    yyaction_44();
yyaction(45, _, _, _, _) ->
    yyaction_45();
yyaction(46, _, _, _, _) ->
    yyaction_46();
yyaction(_, _, _, _, _) -> error.

-compile({inline,yyaction_0/3}).
-file("leex/lx_lexer.xrl", 9).
yyaction_0(TokenChars, TokenLine, TokenCol) ->
     { token, { atom, TokenLine, TokenCol, list_to_atom (lists : sublist (TokenChars, 3, length (TokenChars) - 3)) } } .

-compile({inline,yyaction_1/3}).
-file("leex/lx_lexer.xrl", 10).
yyaction_1(TokenChars, TokenLine, TokenCol) ->
     { token, { integer, TokenLine, TokenCol, list_to_integer (TokenChars) } } .

-compile({inline,yyaction_2/3}).
-file("leex/lx_lexer.xrl", 11).
yyaction_2(TokenChars, TokenLine, TokenCol) ->
     { token, { float, TokenLine, TokenCol, list_to_float (TokenChars) } } .

-compile({inline,yyaction_3/3}).
-file("leex/lx_lexer.xrl", 12).
yyaction_3(TokenChars, TokenLine, TokenCol) ->
     { token, { string, TokenLine, TokenCol, strip_quotes (TokenChars) } } .

-compile({inline,yyaction_4/3}).
-file("leex/lx_lexer.xrl", 13).
yyaction_4(TokenChars, TokenLine, TokenCol) ->
     { token, { atom, TokenLine, TokenCol, strip_colon (TokenChars) } } .

-compile({inline,yyaction_5/2}).
-file("leex/lx_lexer.xrl", 14).
yyaction_5(TokenLine, TokenCol) ->
     { token, { boolean, TokenLine, TokenCol, true } } .

-compile({inline,yyaction_6/2}).
-file("leex/lx_lexer.xrl", 15).
yyaction_6(TokenLine, TokenCol) ->
     { token, { boolean, TokenLine, TokenCol, false } } .

-compile({inline,yyaction_7/2}).
-file("leex/lx_lexer.xrl", 16).
yyaction_7(TokenLine, TokenCol) ->
     { token, { nil, TokenLine, TokenCol, nil } } .

-compile({inline,yyaction_8/2}).
-file("leex/lx_lexer.xrl", 19).
yyaction_8(TokenLine, TokenCol) ->
     { token, { defmacro, TokenLine, TokenCol } } .

-compile({inline,yyaction_9/2}).
-file("leex/lx_lexer.xrl", 20).
yyaction_9(TokenLine, TokenCol) ->
     { token, { infix, TokenLine, TokenCol } } .

-compile({inline,yyaction_10/2}).
-file("leex/lx_lexer.xrl", 21).
yyaction_10(TokenLine, TokenCol) ->
     { token, { do, TokenLine, TokenCol } } .

-compile({inline,yyaction_11/2}).
-file("leex/lx_lexer.xrl", 22).
yyaction_11(TokenLine, TokenCol) ->
     { token, { 'end', TokenLine, TokenCol } } .

-compile({inline,yyaction_12/2}).
-file("leex/lx_lexer.xrl", 23).
yyaction_12(TokenLine, TokenCol) ->
     { token, { '->', TokenLine, TokenCol } } .

-compile({inline,yyaction_13/2}).
-file("leex/lx_lexer.xrl", 26).
yyaction_13(TokenLine, TokenCol) ->
     { token, { '::', TokenLine, TokenCol } } .

-compile({inline,yyaction_14/3}).
-file("leex/lx_lexer.xrl", 30).
yyaction_14(TokenChars, TokenLine, TokenCol) ->
     case TokenChars of
     "Integer" -> { token, { type_identifier, TokenLine, TokenCol, "integer" } } ;
     "Float" -> { token, { type_identifier, TokenLine, TokenCol, "float" } } ;
     "String" -> { token, { type_identifier, TokenLine, TokenCol, "string" } } ;
     "Boolean" -> { token, { type_identifier, TokenLine, TokenCol, "boolean" } } ;
     "Atom" -> { token, { type_identifier, TokenLine, TokenCol, "atom" } } ;
     "Any" -> { token, { type_identifier, TokenLine, TokenCol, "any" } } ;
     "Fun" -> { token, { type_identifier, TokenLine, TokenCol, "fun" } } ;
     "List" -> { token, { type_identifier, TokenLine, TokenCol, "list" } } ;
     "Tuple" -> { token, { type_identifier, TokenLine, TokenCol, "tuple" } } ;
     "Number" -> { token, { type_identifier, TokenLine, TokenCol, "number" } } ;
     "number" -> { token, { type_identifier, TokenLine, TokenCol, "number" } } ;
     _ -> { token, { ident, TokenLine, TokenCol, TokenChars } }
     end .

-compile({inline,yyaction_15/2}).
-file("leex/lx_lexer.xrl", 46).
yyaction_15(TokenLine, TokenCol) ->
     { token, { type_identifier, TokenLine, TokenCol, "integer" } } .

-compile({inline,yyaction_16/2}).
-file("leex/lx_lexer.xrl", 47).
yyaction_16(TokenLine, TokenCol) ->
     { token, { type_identifier, TokenLine, TokenCol, "float" } } .

-compile({inline,yyaction_17/2}).
-file("leex/lx_lexer.xrl", 48).
yyaction_17(TokenLine, TokenCol) ->
     { token, { type_identifier, TokenLine, TokenCol, "string" } } .

-compile({inline,yyaction_18/2}).
-file("leex/lx_lexer.xrl", 49).
yyaction_18(TokenLine, TokenCol) ->
     { token, { type_identifier, TokenLine, TokenCol, "boolean" } } .

-compile({inline,yyaction_19/2}).
-file("leex/lx_lexer.xrl", 50).
yyaction_19(TokenLine, TokenCol) ->
     { token, { type_identifier, TokenLine, TokenCol, "atom" } } .

-compile({inline,yyaction_20/2}).
-file("leex/lx_lexer.xrl", 51).
yyaction_20(TokenLine, TokenCol) ->
     { token, { type_identifier, TokenLine, TokenCol, "any" } } .

-compile({inline,yyaction_21/2}).
-file("leex/lx_lexer.xrl", 52).
yyaction_21(TokenLine, TokenCol) ->
     { token, { type_identifier, TokenLine, TokenCol, "fun" } } .

-compile({inline,yyaction_22/2}).
-file("leex/lx_lexer.xrl", 53).
yyaction_22(TokenLine, TokenCol) ->
     { token, { type_identifier, TokenLine, TokenCol, "list" } } .

-compile({inline,yyaction_23/2}).
-file("leex/lx_lexer.xrl", 54).
yyaction_23(TokenLine, TokenCol) ->
     { token, { type_identifier, TokenLine, TokenCol, "tuple" } } .

-compile({inline,yyaction_24/2}).
-file("leex/lx_lexer.xrl", 55).
yyaction_24(TokenLine, TokenCol) ->
     { token, { type_identifier, TokenLine, TokenCol, "number" } } .

-compile({inline,yyaction_25/2}).
-file("leex/lx_lexer.xrl", 58).
yyaction_25(TokenLine, TokenCol) ->
     { token, { underscore, TokenLine, TokenCol } } .

-compile({inline,yyaction_26/3}).
-file("leex/lx_lexer.xrl", 59).
yyaction_26(TokenChars, TokenLine, TokenCol) ->
     { token, { ident, TokenLine, TokenCol, TokenChars } } .

-compile({inline,yyaction_27/2}).
-file("leex/lx_lexer.xrl", 62).
yyaction_27(TokenLine, TokenCol) ->
     { token, { bind, TokenLine, TokenCol } } .

-compile({inline,yyaction_28/2}).
-file("leex/lx_lexer.xrl", 63).
yyaction_28(TokenLine, TokenCol) ->
     { token, { semicolon, TokenLine, TokenCol } } .

-compile({inline,yyaction_29/2}).
-file("leex/lx_lexer.xrl", 64).
yyaction_29(TokenLine, TokenCol) ->
     { token, { '(', TokenLine, TokenCol } } .

-compile({inline,yyaction_30/2}).
-file("leex/lx_lexer.xrl", 65).
yyaction_30(TokenLine, TokenCol) ->
     { token, { ')', TokenLine, TokenCol } } .

-compile({inline,yyaction_31/2}).
-file("leex/lx_lexer.xrl", 66).
yyaction_31(TokenLine, TokenCol) ->
     { token, { '[', TokenLine, TokenCol } } .

-compile({inline,yyaction_32/2}).
-file("leex/lx_lexer.xrl", 67).
yyaction_32(TokenLine, TokenCol) ->
     { token, { ']', TokenLine, TokenCol } } .

-compile({inline,yyaction_33/2}).
-file("leex/lx_lexer.xrl", 68).
yyaction_33(TokenLine, TokenCol) ->
     { token, { '{', TokenLine, TokenCol } } .

-compile({inline,yyaction_34/2}).
-file("leex/lx_lexer.xrl", 69).
yyaction_34(TokenLine, TokenCol) ->
     { token, { '}', TokenLine, TokenCol } } .

-compile({inline,yyaction_35/2}).
-file("leex/lx_lexer.xrl", 70).
yyaction_35(TokenLine, TokenCol) ->
     { token, { comma, TokenLine, TokenCol } } .

-compile({inline,yyaction_36/2}).
-file("leex/lx_lexer.xrl", 71).
yyaction_36(TokenLine, TokenCol) ->
     { token, { colon, TokenLine, TokenCol } } .

-compile({inline,yyaction_37/2}).
-file("leex/lx_lexer.xrl", 75).
yyaction_37(TokenLine, TokenCol) ->
     { token, { '+', TokenLine, TokenCol } } .

-compile({inline,yyaction_38/2}).
-file("leex/lx_lexer.xrl", 76).
yyaction_38(TokenLine, TokenCol) ->
     { token, { '-', TokenLine, TokenCol } } .

-compile({inline,yyaction_39/2}).
-file("leex/lx_lexer.xrl", 77).
yyaction_39(TokenLine, TokenCol) ->
     { token, { '*', TokenLine, TokenCol } } .

-compile({inline,yyaction_40/2}).
-file("leex/lx_lexer.xrl", 78).
yyaction_40(TokenLine, TokenCol) ->
     { token, { '/', TokenLine, TokenCol } } .

-compile({inline,yyaction_41/2}).
-file("leex/lx_lexer.xrl", 81).
yyaction_41(TokenLine, TokenCol) ->
     { token, { '++', TokenLine, TokenCol } } .

-compile({inline,yyaction_42/2}).
-file("leex/lx_lexer.xrl", 84).
yyaction_42(TokenLine, TokenCol) ->
     { token, { '[', TokenLine, TokenCol } } .

-compile({inline,yyaction_43/2}).
-file("leex/lx_lexer.xrl", 85).
yyaction_43(TokenLine, TokenCol) ->
     { token, { ']', TokenLine, TokenCol } } .

-compile({inline,yyaction_44/0}).
-file("leex/lx_lexer.xrl", 88).
yyaction_44() ->
     skip_token .

-compile({inline,yyaction_45/0}).
-file("leex/lx_lexer.xrl", 89).
yyaction_45() ->
     skip_token .

-compile({inline,yyaction_46/0}).
-file("leex/lx_lexer.xrl", 90).
yyaction_46() ->
     skip_token .
-file("/home/helder/.asdf/installs/erlang/28.0.1/lib/parsetools-2.7/include/leexinc.hrl", 377).
%% Funções customizadas para o lexer
%% Este arquivo é incluído automaticamente após a geração do lexer

%% Tokenize source code
tokenize(Source) ->
    tokenize(Source, []).

tokenize(Source, _Options) ->
    case string(Source) of
        {ok, Tokens, _} ->
            {ok, Tokens};
        {error, ErrorInfo, _} ->
            {error, {lexical_error, ErrorInfo}}
    end.